/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"crypto/tls"
	"fmt"
	"strings"
	"sync"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	redisv1alpha1 "github.com/redguard/redguard/api/v1alpha1"
	"github.com/redguard/redguard/internal/builder"
	"github.com/redguard/redguard/internal/redisclient"
	"github.com/redguard/redguard/internal/redisclient/fake"
)

var _ = Describe("RedisSentinel Controller", func() {
	Context("When reconciling a resource", func() {
		const resourceName = "test-resource"

		// Object names generated by internal/builder. Spelled out as literals so
		// that renaming a generated object breaks this test rather than silently
		// orphaning what is already running in a cluster.
		const (
			redisConfigMapName    = resourceName + "-redis-config"
			sentinelConfigMapName = resourceName + "-sentinel-config"

			redisHeadlessServiceName    = resourceName + "-redis-headless"
			redisServiceName            = resourceName + "-redis"
			redisReplicasServiceName    = resourceName + "-redis-replicas"
			sentinelHeadlessServiceName = resourceName + "-sentinel-headless"
			sentinelServiceName         = resourceName + "-sentinel"

			redisNetworkPolicyName    = resourceName + "-redis-netpol"
			sentinelNetworkPolicyName = resourceName + "-sentinel-netpol"

			redisStatefulSetName    = resourceName + "-redis"
			sentinelStatefulSetName = resourceName + "-sentinel"
		)

		ctx := context.Background()

		typeNamespacedName := types.NamespacedName{
			Name:      resourceName,
			Namespace: "default",
		}
		redissentinel := &redisv1alpha1.RedisSentinel{}

		var controllerReconciler *RedisSentinelReconciler

		BeforeEach(func() {
			By("creating the custom resource for the Kind RedisSentinel")
			err := k8sClient.Get(ctx, typeNamespacedName, redissentinel)
			if err != nil && errors.IsNotFound(err) {
				Expect(k8sClient.Create(ctx, newTestSentinel(resourceName, "default"))).To(Succeed())
			}

			// A fake factory: the default one resolves *.svc.cluster.local
			// per pass, stalling in mDNS for seconds outside a cluster.
			controllerReconciler = &RedisSentinelReconciler{
				Client:       k8sClient,
				Scheme:       k8sClient.Scheme(),
				Recorder:     testRecorder,
				RedisFactory: fake.NewFactory(),
			}
		})

		AfterEach(func() {
			resource := &redisv1alpha1.RedisSentinel{}
			err := k8sClient.Get(ctx, typeNamespacedName, resource)
			Expect(err).NotTo(HaveOccurred())

			By("Cleanup the specific resource instance RedisSentinel")
			Expect(k8sClient.Delete(ctx, resource)).To(Succeed())

			// The reconciler adds a finalizer, so the object only disappears
			// once a reconcile of the deletion has removed it again. The
			// Manager-owned controller does that too; driving it here keeps the
			// cleanup deterministic.
			Eventually(func(g Gomega) {
				_, err := controllerReconciler.Reconcile(ctx, reconcile.Request{NamespacedName: typeNamespacedName})
				g.Expect(err).NotTo(HaveOccurred())
				err = k8sClient.Get(ctx, typeNamespacedName, resource)
				g.Expect(errors.IsNotFound(err)).To(BeTrue())
			}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
		})

		It("should successfully reconcile the resource", func() {
			By("Reconciling the created resource")
			result := reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			Expect(result.RequeueAfter).To(Equal(30 * time.Second))
		})

		It("creates every owned resource with a controller owner reference", func() {
			By("Reconciling the created resource")
			reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			owner := &redisv1alpha1.RedisSentinel{}
			Expect(k8sClient.Get(ctx, typeNamespacedName, owner)).To(Succeed())

			By("checking the generated ConfigMaps")
			for _, name := range []string{redisConfigMapName, sentinelConfigMapName} {
				cm := &corev1.ConfigMap{}
				Expect(k8sClient.Get(ctx, inDefault(name), cm)).To(Succeed())
				expectControlledBy(cm, owner)
				Expect(cm.Data).NotTo(BeEmpty())
			}

			By("checking the generated Services")
			for _, name := range []string{
				redisHeadlessServiceName,
				redisServiceName,
				redisReplicasServiceName,
				sentinelHeadlessServiceName,
				sentinelServiceName,
			} {
				svc := &corev1.Service{}
				Expect(k8sClient.Get(ctx, inDefault(name), svc)).To(Succeed())
				expectControlledBy(svc, owner)
			}

			By("checking that the peer-discovery Services are headless")
			for _, name := range []string{redisHeadlessServiceName, sentinelHeadlessServiceName} {
				svc := &corev1.Service{}
				Expect(k8sClient.Get(ctx, inDefault(name), svc)).To(Succeed())
				Expect(svc.Spec.ClusterIP).To(Equal(corev1.ClusterIPNone))
				// StatefulSet DNS records must exist before a pod is ready,
				// otherwise the sentinel peers can never resolve each other.
				Expect(svc.Spec.PublishNotReadyAddresses).To(BeTrue())
			}

			By("checking the generated NetworkPolicies")
			for _, name := range []string{redisNetworkPolicyName, sentinelNetworkPolicyName} {
				netpol := &networkingv1.NetworkPolicy{}
				Expect(k8sClient.Get(ctx, inDefault(name), netpol)).To(Succeed())
				expectControlledBy(netpol, owner)
				Expect(netpol.Spec.PolicyTypes).To(ConsistOf(
					networkingv1.PolicyTypeIngress,
					networkingv1.PolicyTypeEgress,
				))
			}

			By("checking the Redis StatefulSet")
			redisSts := &appsv1.StatefulSet{}
			Expect(k8sClient.Get(ctx, inDefault(redisStatefulSetName), redisSts)).To(Succeed())
			expectControlledBy(redisSts, owner)
			Expect(redisSts.Spec.Replicas).To(HaveValue(Equal(owner.Spec.RedisConfig.Replicas)))
			Expect(redisSts.Spec.Replicas).To(HaveValue(Equal(int32(3))))
			Expect(redisSts.Spec.ServiceName).To(Equal(redisHeadlessServiceName))

			By("checking the Sentinel StatefulSet")
			sentinelSts := &appsv1.StatefulSet{}
			Expect(k8sClient.Get(ctx, inDefault(sentinelStatefulSetName), sentinelSts)).To(Succeed())
			expectControlledBy(sentinelSts, owner)
			Expect(sentinelSts.Spec.Replicas).To(HaveValue(Equal(owner.Spec.SentinelConfig.Replicas)))
			Expect(sentinelSts.Spec.Replicas).To(HaveValue(Equal(int32(3))))
			Expect(sentinelSts.Spec.ServiceName).To(Equal(sentinelHeadlessServiceName))
		})

		It("recreates owned resources that are deleted out from under it", func() {
			By("Reconciling the created resource")
			reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			// One representative of every kind the reconciler owns. UIDs are
			// captured first so the assertion proves a genuine recreate rather
			// than a stale read of the object that was deleted.
			drifted := []client.Object{
				&corev1.ConfigMap{},
				&corev1.Service{},
				&networkingv1.NetworkPolicy{},
				&appsv1.StatefulSet{},
			}
			keys := []types.NamespacedName{
				inDefault(redisConfigMapName),
				inDefault(redisServiceName),
				inDefault(redisNetworkPolicyName),
				inDefault(redisStatefulSetName),
			}

			originalUIDs := make([]types.UID, len(drifted))
			for i, obj := range drifted {
				Expect(k8sClient.Get(ctx, keys[i], obj)).To(Succeed())
				originalUIDs[i] = obj.GetUID()
			}

			By("deleting the owned resources")
			for _, obj := range drifted {
				Expect(k8sClient.Delete(ctx, obj)).To(Succeed())
			}

			// The Manager runs the same reconciler and its Owns() watch reacts to
			// the deletes, so the repair may come from either reconciler. Both are
			// the operator repairing drift, which is what this asserts; waiting for
			// the objects to be observably absent first would only add a race.
			By("reconciling again and expecting the drift to be repaired")
			reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			owner := &redisv1alpha1.RedisSentinel{}
			Expect(k8sClient.Get(ctx, typeNamespacedName, owner)).To(Succeed())

			for i, obj := range drifted {
				recreated := obj.DeepCopyObject().(client.Object)
				Expect(k8sClient.Get(ctx, keys[i], recreated)).To(Succeed(), "%s was not recreated", keys[i])
				Expect(recreated.GetUID()).NotTo(Equal(originalUIDs[i]), "%s was not actually recreated", keys[i])
				expectControlledBy(recreated, owner)
			}
		})
	})
})

var _ = Describe("RedisSentinel master labeling", func() {
	const resourceName = "labeling-rs"

	ctx := context.Background()
	key := types.NamespacedName{Name: resourceName, Namespace: "default"}
	podIPs := []string{"10.244.9.10", "10.244.9.11", "10.244.9.12"}

	var (
		fakeFactory *fake.Factory
		reconciler  *RedisSentinelReconciler
		podNames    []string
	)

	BeforeEach(func() {
		fakeFactory = fake.NewFactory()
		reconciler = &RedisSentinelReconciler{
			Client:       k8sClient,
			Scheme:       k8sClient.Scheme(),
			Recorder:     testRecorder,
			RedisFactory: fakeFactory,
		}

		Expect(k8sClient.Create(ctx, newTestSentinel(resourceName, "default"))).To(Succeed())
		reconcileUntilSettled(ctx, reconciler, key)

		rs := &redisv1alpha1.RedisSentinel{}
		Expect(k8sClient.Get(ctx, key, rs)).To(Succeed())

		// envtest runs no kubelet or StatefulSet controller, so the pods and
		// the StatefulSet statuses that would exist in a live cluster are
		// created by hand.
		markStatefulSetReady(ctx, inDefault(resourceName+"-redis"), 3)
		markStatefulSetReady(ctx, inDefault(resourceName+"-sentinel"), 3)

		template := builder.BuildRedisStatefulSet(rs).Spec.Template
		podNames = nil
		for i, ip := range podIPs {
			name := fmt.Sprintf("%s-redis-%d", resourceName, i)
			createRunningPod(ctx, name, template.Labels, ip)
			podNames = append(podNames, name)
		}
	})

	AfterEach(func() {
		for _, name := range podNames {
			pod := &corev1.Pod{}
			pod.Name, pod.Namespace = name, "default"
			_ = k8sClient.Delete(ctx, pod, client.GracePeriodSeconds(0))
		}

		rs := &redisv1alpha1.RedisSentinel{}
		Expect(k8sClient.Get(ctx, key, rs)).To(Succeed())
		Expect(k8sClient.Delete(ctx, rs)).To(Succeed())
		Eventually(func(g Gomega) {
			_, err := reconciler.Reconcile(ctx, reconcile.Request{NamespacedName: key})
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(errors.IsNotFound(k8sClient.Get(ctx, key, rs))).To(BeTrue())
		}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
	})

	It("stamps the master pod and moves the label after a failover", func() {
		By("labeling the pod Sentinel reports as master")
		fakeFactory.SetMaster(podIPs[0] + ":6379")
		result := reconcileUntilSettled(ctx, reconciler, key)
		expectMasterLabelOnlyOn(ctx, podNames, podNames[0])
		Expect(result.RequeueAfter).To(Equal(30*time.Second),
			"a labeled master needs no fast requeue")

		By("moving the label when Sentinel promotes another pod")
		fakeFactory.SetMaster(podIPs[1] + ":6379")
		reconcileUntilSettled(ctx, reconciler, key)
		expectMasterLabelOnlyOn(ctx, podNames, podNames[1])

		rs := &redisv1alpha1.RedisSentinel{}
		Expect(k8sClient.Get(ctx, key, rs)).To(Succeed())
		Expect(rs.Status.MasterNode).To(Equal(podIPs[1] + ":6379"))
		Expect(rs.Status.LastFailoverTime).NotTo(BeNil(),
			"the master change was not detected as a failover")
	})

	It("requeues fast while the reported master matches no running pod", func() {
		// The state mid-failover: Sentinel still names the dead pod's IP. The
		// label must not sit on the 30s periodic pass, or the write Service
		// points nowhere for up to 30s after Sentinel has already promoted.
		fakeFactory.SetMaster("10.255.0.99:6379")
		result := reconcileUntilSettled(ctx, reconciler, key)

		Expect(result.RequeueAfter).To(Equal(5*time.Second),
			"an unresolvable master must be retried quickly, not on the periodic pass")
		expectMasterLabelOnlyOn(ctx, podNames, "")
	})

	It("requeues fast while Sentinel cannot name a master", func() {
		result := reconcileUntilSettled(ctx, reconciler, key)

		Expect(result.RequeueAfter).To(Equal(5 * time.Second))
		expectMasterLabelOnlyOn(ctx, podNames, "")
	})
})

var _ = Describe("RedisSentinel failover handling", func() {
	const resourceName = "failover-rs"

	ctx := context.Background()
	key := types.NamespacedName{Name: resourceName, Namespace: "default"}
	podIPs := []string{"10.244.11.10", "10.244.11.11", "10.244.11.12"}

	var (
		fakeFactory *fake.Factory
		factory     *flippingFactory
		reconciler  *RedisSentinelReconciler
		podNames    []string
	)

	BeforeEach(func() {
		fakeFactory = fake.NewFactory()
		factory = &flippingFactory{Factory: fakeFactory}
		reconciler = &RedisSentinelReconciler{
			Client:       k8sClient,
			Scheme:       k8sClient.Scheme(),
			Recorder:     testRecorder,
			RedisFactory: factory,
		}

		Expect(k8sClient.Create(ctx, newTestSentinel(resourceName, "default"))).To(Succeed())
		reconcileUntilSettled(ctx, reconciler, key)

		rs := &redisv1alpha1.RedisSentinel{}
		Expect(k8sClient.Get(ctx, key, rs)).To(Succeed())

		markStatefulSetReady(ctx, inDefault(resourceName+"-redis"), 3)
		markStatefulSetReady(ctx, inDefault(resourceName+"-sentinel"), 3)

		template := builder.BuildRedisStatefulSet(rs).Spec.Template
		podNames = nil
		for i, ip := range podIPs {
			name := fmt.Sprintf("%s-redis-%d", resourceName, i)
			createRunningPod(ctx, name, template.Labels, ip)
			podNames = append(podNames, name)
		}
	})

	AfterEach(func() {
		for _, name := range podNames {
			pod := &corev1.Pod{}
			pod.Name, pod.Namespace = name, "default"
			_ = k8sClient.Delete(ctx, pod, client.GracePeriodSeconds(0))
		}

		rs := &redisv1alpha1.RedisSentinel{}
		Expect(k8sClient.Get(ctx, key, rs)).To(Succeed())
		Expect(k8sClient.Delete(ctx, rs)).To(Succeed())
		Eventually(func(g Gomega) {
			_, err := reconciler.Reconcile(ctx, reconcile.Request{NamespacedName: key})
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(errors.IsNotFound(k8sClient.Get(ctx, key, rs))).To(BeTrue())
		}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
	})

	It("abandons the reconfiguration when the master moves again mid-handling", func() {
		By("establishing the initial master")
		fakeFactory.SetMaster(podIPs[0] + ":6379")
		reconcileUntilSettled(ctx, reconciler, key)
		expectMasterLabelOnlyOn(ctx, podNames, podNames[0])

		By("failing over to pod 1 with a second failover to pod 2 landing after detection")
		var result reconcile.Result
		Eventually(func() error {
			// Re-armed on every attempt so a conflict retry sees the same
			// sequence: detection answers pod 1, the re-check answers pod 2.
			fakeFactory.SetMaster(podIPs[1] + ":6379")
			factory.armFlip(podIPs[2] + ":6379")
			var err error
			result, err = reconciler.Reconcile(ctx, reconcile.Request{NamespacedName: key})
			return err
		}, 20*time.Second, 200*time.Millisecond).Should(Succeed())

		By("verifying no node was reconfigured from the stale snapshot")
		Consistently(func() []string { return slaveOfCalls(fakeFactory) },
			2*time.Second, 100*time.Millisecond).Should(BeEmpty(),
			"a SLAVEOF issued mid-failover can demote the freshly promoted master")

		Expect(result.RequeueAfter).To(Equal(failoverRequeue),
			"an abandoned reconfiguration must be retried on the fast requeue")

		By("converging on the final master on the next pass")
		reconcileUntilSettled(ctx, reconciler, key)
		expectMasterLabelOnlyOn(ctx, podNames, podNames[2])
		Expect(slaveOfCalls(fakeFactory)).NotTo(ContainElement(podIPs[2]+":6379:SlaveOf"),
			"the promoted master must never be demoted; that discards its acknowledged writes")
	})

	It("demotes the stale master inline once Sentinel confirms the promotion", func() {
		By("establishing the initial master")
		fakeFactory.SetMaster(podIPs[0] + ":6379")
		reconcileUntilSettled(ctx, reconciler, key)

		By("failing over to pod 1 and reconciling")
		fakeFactory.SetMaster(podIPs[1] + ":6379")
		reconcileUntilSettled(ctx, reconciler, key)

		// Inline handling: the demotion is already recorded when Reconcile
		// returns. Nothing here waits on a goroutine.
		calls := slaveOfCalls(fakeFactory)
		Expect(calls).NotTo(BeEmpty(),
			"the stale master was never told to follow the promoted one")
		Expect(calls).To(HaveEach(Equal(podIPs[0]+":6379:SlaveOf")),
			"only the stale master may be reconfigured after a confirmed failover")
		expectMasterLabelOnlyOn(ctx, podNames, podNames[1])
	})
})

// flippingFactory wraps the fake factory and moves the master to the armed
// address right after the next GetMasterAddrFromPool answer, reproducing a
// second failover landing between detection and reconfiguration.
type flippingFactory struct {
	*fake.Factory
	mu     sync.Mutex
	flipTo string
}

func (f *flippingFactory) armFlip(addr string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.flipTo = addr
}

func (f *flippingFactory) NewSentinelPool(addrs []string, password string, tlsConfig *tls.Config) redisclient.Sentinel {
	return &flippingPool{Sentinel: f.Factory.NewSentinelPool(addrs, password, tlsConfig), f: f}
}

type flippingPool struct {
	redisclient.Sentinel
	f *flippingFactory
}

func (p *flippingPool) GetMasterAddrFromPool(ctx context.Context, masterName string) (string, error) {
	addr, err := p.Sentinel.GetMasterAddrFromPool(ctx, masterName)
	p.f.mu.Lock()
	to := p.f.flipTo
	p.f.flipTo = ""
	p.f.mu.Unlock()
	if to != "" {
		p.f.Factory.SetMaster(to)
	}
	return addr, err
}

// slaveOfCalls filters the factory call log down to SlaveOf entries.
func slaveOfCalls(f *fake.Factory) []string {
	var out []string
	for _, c := range f.Calls() {
		if strings.HasSuffix(c, ":SlaveOf") {
			out = append(out, c)
		}
	}
	return out
}

// inDefault builds a key in the namespace the sentinel specs use.
func inDefault(name string) types.NamespacedName {
	return types.NamespacedName{Name: name, Namespace: "default"}
}

// markStatefulSetReady fakes the status a StatefulSet controller would report
// for a fully available StatefulSet.
func markStatefulSetReady(ctx context.Context, key types.NamespacedName, replicas int32) {
	GinkgoHelper()

	Eventually(func(g Gomega) {
		sts := &appsv1.StatefulSet{}
		g.Expect(k8sClient.Get(ctx, key, sts)).To(Succeed())
		sts.Status.ObservedGeneration = sts.Generation
		sts.Status.Replicas = replicas
		sts.Status.ReadyReplicas = replicas
		sts.Status.AvailableReplicas = replicas
		g.Expect(k8sClient.Status().Update(ctx, sts)).To(Succeed())
	}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
}

// createRunningPod creates a pod carrying the given labels and forces its
// status to Running with the given IP, standing in for a kubelet.
func createRunningPod(ctx context.Context, name string, labels map[string]string, ip string) {
	GinkgoHelper()

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: "default", Labels: labels},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{{Name: "redis", Image: "redis:7-alpine"}},
		},
	}
	Expect(k8sClient.Create(ctx, pod)).To(Succeed())

	pod.Status.Phase = corev1.PodRunning
	pod.Status.PodIP = ip
	Expect(k8sClient.Status().Update(ctx, pod)).To(Succeed())
}

// expectMasterLabelOnlyOn asserts exactly one pod (or none, for master == "")
// carries the master role label.
func expectMasterLabelOnlyOn(ctx context.Context, podNames []string, master string) {
	GinkgoHelper()

	for _, name := range podNames {
		pod := &corev1.Pod{}
		Expect(k8sClient.Get(ctx, inDefault(name), pod)).To(Succeed())
		if name == master {
			Expect(pod.Labels).To(HaveKeyWithValue(builder.RoleLabelKey, builder.RoleMaster),
				"%s is the master but does not carry the role label; the write Service has no endpoints", name)
		} else {
			Expect(pod.Labels).NotTo(HaveKey(builder.RoleLabelKey),
				"%s is not the master but still carries the role label; writes would reach a replica", name)
		}
	}
}

// reconcileUntilSettled drives a spec-owned reconciler until it returns without
// error. The same reconciler also runs inside the Manager, so a single manual
// call can lose an optimistic-concurrency race on the RedisSentinel itself, on
// the finalizer or the status write. Races on owned objects are retried inside
// createOrUpdate and never reach here.
func reconcileUntilSettled(ctx context.Context, r *RedisSentinelReconciler, key types.NamespacedName) reconcile.Result {
	GinkgoHelper()

	var result reconcile.Result
	Eventually(func() error {
		var err error
		result, err = r.Reconcile(ctx, reconcile.Request{NamespacedName: key})
		return err
	}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
	return result
}

// expectControlledBy asserts obj carries exactly one owner reference and that it
// is a controller reference to owner, which is what makes Kubernetes garbage
// collect the object with its RedisSentinel and what makes Owns() watches fire.
func expectControlledBy(obj client.Object, owner *redisv1alpha1.RedisSentinel) {
	GinkgoHelper()

	refs := obj.GetOwnerReferences()
	Expect(refs).To(HaveLen(1), "%T %s owner references", obj, obj.GetName())
	Expect(refs[0].APIVersion).To(Equal(redisv1alpha1.GroupVersion.String()))
	Expect(refs[0].Kind).To(Equal("RedisSentinel"))
	Expect(refs[0].Name).To(Equal(owner.Name))
	Expect(refs[0].UID).To(Equal(owner.UID))
	Expect(refs[0].Controller).To(HaveValue(BeTrue()))
	Expect(refs[0].BlockOwnerDeletion).To(HaveValue(BeTrue()))
}
