/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	redisv1alpha1 "github.com/redguard/redguard/api/v1alpha1"
)

var _ = Describe("RedisSentinel Controller", func() {
	Context("When reconciling a resource", func() {
		const resourceName = "test-resource"

		// Object names generated by internal/builder. Spelled out as literals so
		// that renaming a generated object breaks this test rather than silently
		// orphaning what is already running in a cluster.
		const (
			redisConfigMapName    = resourceName + "-redis-config"
			sentinelConfigMapName = resourceName + "-sentinel-config"

			redisHeadlessServiceName    = resourceName + "-redis-headless"
			redisServiceName            = resourceName + "-redis"
			sentinelHeadlessServiceName = resourceName + "-sentinel-headless"
			sentinelServiceName         = resourceName + "-sentinel"

			redisNetworkPolicyName    = resourceName + "-redis-netpol"
			sentinelNetworkPolicyName = resourceName + "-sentinel-netpol"

			redisStatefulSetName    = resourceName + "-redis"
			sentinelStatefulSetName = resourceName + "-sentinel"
		)

		ctx := context.Background()

		typeNamespacedName := types.NamespacedName{
			Name:      resourceName,
			Namespace: "default",
		}
		redissentinel := &redisv1alpha1.RedisSentinel{}

		var controllerReconciler *RedisSentinelReconciler

		BeforeEach(func() {
			By("creating the custom resource for the Kind RedisSentinel")
			err := k8sClient.Get(ctx, typeNamespacedName, redissentinel)
			if err != nil && errors.IsNotFound(err) {
				Expect(k8sClient.Create(ctx, newTestSentinel(resourceName, "default"))).To(Succeed())
			}

			controllerReconciler = &RedisSentinelReconciler{
				Client:   k8sClient,
				Scheme:   k8sClient.Scheme(),
				Recorder: testRecorder,
			}
		})

		AfterEach(func() {
			resource := &redisv1alpha1.RedisSentinel{}
			err := k8sClient.Get(ctx, typeNamespacedName, resource)
			Expect(err).NotTo(HaveOccurred())

			By("Cleanup the specific resource instance RedisSentinel")
			Expect(k8sClient.Delete(ctx, resource)).To(Succeed())

			// The reconciler adds a finalizer, so the object only disappears
			// once a reconcile of the deletion has removed it again. The
			// Manager-owned controller does that too; driving it here keeps the
			// cleanup deterministic.
			Eventually(func(g Gomega) {
				_, err := controllerReconciler.Reconcile(ctx, reconcile.Request{NamespacedName: typeNamespacedName})
				g.Expect(err).NotTo(HaveOccurred())
				err = k8sClient.Get(ctx, typeNamespacedName, resource)
				g.Expect(errors.IsNotFound(err)).To(BeTrue())
			}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
		})

		It("should successfully reconcile the resource", func() {
			By("Reconciling the created resource")
			result := reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			Expect(result.RequeueAfter).To(Equal(30 * time.Second))
		})

		It("creates every owned resource with a controller owner reference", func() {
			By("Reconciling the created resource")
			reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			owner := &redisv1alpha1.RedisSentinel{}
			Expect(k8sClient.Get(ctx, typeNamespacedName, owner)).To(Succeed())

			By("checking the generated ConfigMaps")
			for _, name := range []string{redisConfigMapName, sentinelConfigMapName} {
				cm := &corev1.ConfigMap{}
				Expect(k8sClient.Get(ctx, inDefault(name), cm)).To(Succeed())
				expectControlledBy(cm, owner)
				Expect(cm.Data).NotTo(BeEmpty())
			}

			By("checking the generated Services")
			for _, name := range []string{
				redisHeadlessServiceName,
				redisServiceName,
				sentinelHeadlessServiceName,
				sentinelServiceName,
			} {
				svc := &corev1.Service{}
				Expect(k8sClient.Get(ctx, inDefault(name), svc)).To(Succeed())
				expectControlledBy(svc, owner)
			}

			By("checking that the peer-discovery Services are headless")
			for _, name := range []string{redisHeadlessServiceName, sentinelHeadlessServiceName} {
				svc := &corev1.Service{}
				Expect(k8sClient.Get(ctx, inDefault(name), svc)).To(Succeed())
				Expect(svc.Spec.ClusterIP).To(Equal(corev1.ClusterIPNone))
				// StatefulSet DNS records must exist before a pod is ready,
				// otherwise the sentinel peers can never resolve each other.
				Expect(svc.Spec.PublishNotReadyAddresses).To(BeTrue())
			}

			By("checking the generated NetworkPolicies")
			for _, name := range []string{redisNetworkPolicyName, sentinelNetworkPolicyName} {
				netpol := &networkingv1.NetworkPolicy{}
				Expect(k8sClient.Get(ctx, inDefault(name), netpol)).To(Succeed())
				expectControlledBy(netpol, owner)
				Expect(netpol.Spec.PolicyTypes).To(ConsistOf(
					networkingv1.PolicyTypeIngress,
					networkingv1.PolicyTypeEgress,
				))
			}

			By("checking the Redis StatefulSet")
			redisSts := &appsv1.StatefulSet{}
			Expect(k8sClient.Get(ctx, inDefault(redisStatefulSetName), redisSts)).To(Succeed())
			expectControlledBy(redisSts, owner)
			Expect(redisSts.Spec.Replicas).To(HaveValue(Equal(owner.Spec.RedisConfig.Replicas)))
			Expect(redisSts.Spec.Replicas).To(HaveValue(Equal(int32(3))))
			Expect(redisSts.Spec.ServiceName).To(Equal(redisHeadlessServiceName))

			By("checking the Sentinel StatefulSet")
			sentinelSts := &appsv1.StatefulSet{}
			Expect(k8sClient.Get(ctx, inDefault(sentinelStatefulSetName), sentinelSts)).To(Succeed())
			expectControlledBy(sentinelSts, owner)
			Expect(sentinelSts.Spec.Replicas).To(HaveValue(Equal(owner.Spec.SentinelConfig.Replicas)))
			Expect(sentinelSts.Spec.Replicas).To(HaveValue(Equal(int32(3))))
			Expect(sentinelSts.Spec.ServiceName).To(Equal(sentinelHeadlessServiceName))
		})

		It("recreates owned resources that are deleted out from under it", func() {
			By("Reconciling the created resource")
			reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			// One representative of every kind the reconciler owns. UIDs are
			// captured first so the assertion proves a genuine recreate rather
			// than a stale read of the object that was deleted.
			drifted := []client.Object{
				&corev1.ConfigMap{},
				&corev1.Service{},
				&networkingv1.NetworkPolicy{},
				&appsv1.StatefulSet{},
			}
			keys := []types.NamespacedName{
				inDefault(redisConfigMapName),
				inDefault(redisServiceName),
				inDefault(redisNetworkPolicyName),
				inDefault(redisStatefulSetName),
			}

			originalUIDs := make([]types.UID, len(drifted))
			for i, obj := range drifted {
				Expect(k8sClient.Get(ctx, keys[i], obj)).To(Succeed())
				originalUIDs[i] = obj.GetUID()
			}

			By("deleting the owned resources")
			for _, obj := range drifted {
				Expect(k8sClient.Delete(ctx, obj)).To(Succeed())
			}

			// The Manager runs the same reconciler and its Owns() watch reacts to
			// the deletes, so the repair may come from either reconciler. Both are
			// the operator repairing drift, which is what this asserts; waiting for
			// the objects to be observably absent first would only add a race.
			By("reconciling again and expecting the drift to be repaired")
			reconcileUntilSettled(ctx, controllerReconciler, typeNamespacedName)

			owner := &redisv1alpha1.RedisSentinel{}
			Expect(k8sClient.Get(ctx, typeNamespacedName, owner)).To(Succeed())

			for i, obj := range drifted {
				recreated := obj.DeepCopyObject().(client.Object)
				Expect(k8sClient.Get(ctx, keys[i], recreated)).To(Succeed(), "%s was not recreated", keys[i])
				Expect(recreated.GetUID()).NotTo(Equal(originalUIDs[i]), "%s was not actually recreated", keys[i])
				expectControlledBy(recreated, owner)
			}
		})
	})
})

// inDefault builds a key in the namespace the sentinel specs use.
func inDefault(name string) types.NamespacedName {
	return types.NamespacedName{Name: name, Namespace: "default"}
}

// reconcileUntilSettled drives a spec-owned reconciler until it returns without
// error. The same reconciler also runs inside the Manager, so a single manual
// call can lose an optimistic-concurrency race (409 Conflict / AlreadyExists).
func reconcileUntilSettled(ctx context.Context, r *RedisSentinelReconciler, key types.NamespacedName) reconcile.Result {
	GinkgoHelper()

	var result reconcile.Result
	Eventually(func() error {
		var err error
		result, err = r.Reconcile(ctx, reconcile.Request{NamespacedName: key})
		return err
	}, 20*time.Second, 200*time.Millisecond).Should(Succeed())
	return result
}

// expectControlledBy asserts obj carries exactly one owner reference and that it
// is a controller reference to owner, which is what makes Kubernetes garbage
// collect the object with its RedisSentinel and what makes Owns() watches fire.
func expectControlledBy(obj client.Object, owner *redisv1alpha1.RedisSentinel) {
	GinkgoHelper()

	refs := obj.GetOwnerReferences()
	Expect(refs).To(HaveLen(1), "%T %s owner references", obj, obj.GetName())
	Expect(refs[0].APIVersion).To(Equal(redisv1alpha1.GroupVersion.String()))
	Expect(refs[0].Kind).To(Equal("RedisSentinel"))
	Expect(refs[0].Name).To(Equal(owner.Name))
	Expect(refs[0].UID).To(Equal(owner.UID))
	Expect(refs[0].Controller).To(HaveValue(BeTrue()))
	Expect(refs[0].BlockOwnerDeletion).To(HaveValue(BeTrue()))
}
