#!/usr/bin/env bash
# Regenerate the chart's CRDs and RBAC from config/, the kubebuilder source of
# truth. Given an output directory the tree is written there instead of into the
# chart, which is how 'make verify-chart' detects drift without mutating files.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$REPO_ROOT/charts/redguard}"

mkdir -p "$OUT/crds" "$OUT/templates"

# Everything from the 'rules:' line to EOF, verbatim: the chart must consume the
# generated rules, never restate them.
rules_of() {
	sed -n '/^rules:/,$p' "$REPO_ROOT/config/rbac/$1"
}

# Whatever bases exist at run time, so a new API needs no edit here.
rm -f "$OUT"/crds/*.yaml
cp "$REPO_ROOT"/config/crd/bases/*.yaml "$OUT/crds/"

{
	cat <<'HEADER'
{{/*
Generated by hack/sync-chart.sh from config/rbac/role.yaml. Do not edit.
*/}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "redguard.fullname" . }}-manager-role
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
HEADER
	rules_of role.yaml
	echo '{{- end }}'
} >"$OUT/templates/role.yaml"

cat <<'BINDING' >"$OUT/templates/rolebinding.yaml"
{{/*
Generated by hack/sync-chart.sh. Do not edit.
*/}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redguard.fullname" . }}-manager-rolebinding
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redguard.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "redguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
BINDING

# Leader election is namespaced: the manager holds its lease in the release
# namespace, so these rules must not live in the ClusterRole.
{
	cat <<'HEADER'
{{/*
Generated by hack/sync-chart.sh from config/rbac/leader_election_role.yaml. Do not edit.
*/}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "redguard.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
HEADER
	rules_of leader_election_role.yaml
	echo '{{- end }}'
} >"$OUT/templates/leader-election-role.yaml"

cat <<'BINDING' >"$OUT/templates/leader-election-rolebinding.yaml"
{{/*
Generated by hack/sync-chart.sh. Do not edit.
*/}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "redguard.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "redguard.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "redguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
BINDING

# The metrics endpoint is served with authn/authz, which delegates to the API
# server; without these the scrape is rejected.
{
	cat <<'HEADER'
{{/*
Generated by hack/sync-chart.sh from config/rbac/metrics_auth_role.yaml. Do not edit.
*/}}
{{- if and .Values.rbac.create .Values.metrics.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "redguard.fullname" . }}-metrics-auth-role
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
HEADER
	rules_of metrics_auth_role.yaml
	echo '{{- end }}'
} >"$OUT/templates/metrics-auth-role.yaml"

cat <<'BINDING' >"$OUT/templates/metrics-auth-rolebinding.yaml"
{{/*
Generated by hack/sync-chart.sh. Do not edit.
*/}}
{{- if and .Values.rbac.create .Values.metrics.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redguard.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redguard.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "redguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
BINDING

echo "chart synced from config/ into $OUT"
